-- =====================================================
-- Golf Data Quality: Supabase Migration
-- Generated: 2026-02-11
-- =====================================================
-- This migration adds data quality infrastructure to
-- the Supabase database to match what was created in
-- the local SQLite database.
-- =====================================================

-- 1. Add is_warmup column to shots table
-- This column enables dashboard toggle for warmup shot filtering.
-- 0 = not a warmup shot, 1 = warmup shot
ALTER TABLE shots ADD COLUMN IF NOT EXISTS is_warmup INTEGER DEFAULT 0;

-- 2. Create shot_quality_flags table
-- Stores quality flags generated by the data quality validator.
-- Each flag links a shot_id to a category, severity, and reason.
CREATE TABLE IF NOT EXISTS shot_quality_flags (
    flag_id BIGSERIAL PRIMARY KEY,
    shot_id TEXT NOT NULL,
    category TEXT NOT NULL,
    severity TEXT NOT NULL CHECK (severity IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')),
    reason TEXT NOT NULL,
    flagged_at TIMESTAMPTZ DEFAULT NOW(),
    session_id TEXT,
    club TEXT
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_sqf_shot_id ON shot_quality_flags (shot_id);
CREATE INDEX IF NOT EXISTS idx_sqf_severity ON shot_quality_flags (severity);
CREATE INDEX IF NOT EXISTS idx_sqf_category ON shot_quality_flags (category);
CREATE INDEX IF NOT EXISTS idx_sqf_session_id ON shot_quality_flags (session_id);

-- 3. Create shots_clean view
-- Excludes shots with CRITICAL or HIGH severity flags.
-- Use this view for general analytics — removes bad data but
-- keeps warmup and other context shots (filter those with is_warmup).
CREATE OR REPLACE VIEW shots_clean AS
SELECT s.*
FROM shots s
WHERE NOT EXISTS (
    SELECT 1 FROM shot_quality_flags f
    WHERE f.shot_id = s.shot_id
      AND f.severity IN ('CRITICAL', 'HIGH')
);

-- 4. Create shots_strict view
-- Excludes shots with CRITICAL, HIGH, or MEDIUM severity flags.
-- Use this view for maximum data purity — also excludes warmup,
-- unusual spin rates, etc. Best for ML training and club gapping.
CREATE OR REPLACE VIEW shots_strict AS
SELECT s.*
FROM shots s
WHERE NOT EXISTS (
    SELECT 1 FROM shot_quality_flags f
    WHERE f.shot_id = s.shot_id
      AND f.severity IN ('CRITICAL', 'HIGH', 'MEDIUM')
);

-- 5. Enable RLS (Row Level Security) on shot_quality_flags
-- Match the same policy pattern as other tables.
ALTER TABLE shot_quality_flags ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read flags
CREATE POLICY "Allow authenticated read on shot_quality_flags"
    ON shot_quality_flags
    FOR SELECT
    TO authenticated
    USING (true);

-- Allow service role full access (for sync operations)
CREATE POLICY "Allow service role full access on shot_quality_flags"
    ON shot_quality_flags
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);
